<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('qbus')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_qbus.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('qbus.so')) return;
    } else {
      if (!dl('qbus.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}

class QbusProducer {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_qbus_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __get($var) {
		if ($var === 'thisown') return swig_qbus_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_qbus__QbusProducer') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_QbusProducer();
	}

	function init($cluster_name,$log_path,$config_path,$topic_name) {
		return QbusProducer_init($this->_cPtr,$cluster_name,$log_path,$config_path,$topic_name);
	}

	function uninit() {
		QbusProducer_uninit($this->_cPtr);
	}

	function produce($data,$data_len,$key) {
		return QbusProducer_produce($this->_cPtr,$data,$data_len,$key);
	}
}

