interest_data = [
{"areaname":"全部","arealevel":"0","areacode":"9999","parentareacode": "0"},
{"areaname":"游戏","arealevel":"0","areacode":"1","parentareacode": "0"},
{"areaname":"视频","arealevel":"0","areacode":"2","parentareacode": "0"},
{"areaname":"小说","arealevel":"0","areacode":"3","parentareacode": "0"},
{"areaname":"音乐","arealevel":"0","areacode":"4","parentareacode": "0"},
{"areaname":"安全购物","arealevel":"0","areacode":"5","parentareacode": "0"},
{"areaname":"生活","arealevel":"0","areacode":"6","parentareacode": "0"},
{"areaname":"儿童","arealevel":"0","areacode":"7","parentareacode": "0"},
{"areaname":"时尚娱乐","arealevel":"0","areacode":"8","parentareacode": "0"},
{"areaname":"实用工具","arealevel":"0","areacode":"9","parentareacode": "0"},
{"areaname":"投资理财","arealevel":"0","areacode":"10","parentareacode": "0"},
{"areaname":"图片","arealevel":"0","areacode":"11","parentareacode": "0"},
{"areaname":"杂志漫画","arealevel":"0","areacode":"12","parentareacode": "0"},
{"areaname":"安全网银","arealevel":"0","areacode":"13","parentareacode": "0"},
{"areaname":"社交","arealevel":"0","areacode":"14","parentareacode": "0"},
{"areaname":"新闻","arealevel":"0","areacode":"15","parentareacode": "0"},
{"areaname":"教育","arealevel":"0","areacode":"16","parentareacode": "0"}]
